---
- name: Become Block
  become: "{{ drupal_core_owner_become }}"
  become_user: "{{ drupal_core_owner }}"
  block:
    - name: Set Config Fact
      set_fact:
        drupal_generic_config: openid_connect.settings.generic
    - name: Get current generic openid config
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cget {{ drupal_generic_config }}"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      register: drupal_generic_yaml
      failed_when: "drupal_generic_yaml.stdout is undefined"
      changed_when: false
    - name: Set Config Object Fact
      set_fact:
        current_generic_config: "{{ drupal_generic_yaml.stdout | from_yaml }}"
    - name: Set generic openid Enabled
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cset {{ drupal_generic_config }} enabled generic"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      when: "current_generic_config.enabled != 'generic'"
    - name: Set Client ID
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cset {{ drupal_generic_config }} settings.client_id {{ keycloak_client_id }}"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      when: "current_generic_config.settings.client_id != keycloak_client_id"
    - name: Set Client Secret
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cset {{ drupal_generic_config }} settings.client_secret {{ keycloak_client_secret }}"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      when: "current_generic_config.settings.client_secret != keycloak_client_secret"
    - name: Set Keycloak Authorization URL
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cset {{ drupal_generic_config }} settings.authorization_endpoint {{ keycloak_auth_url }}"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      when: "current_generic_config.settings.authorization_endpoint != keycloak_auth_url"
    - name: Set Keycloak Token URL
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cset {{ drupal_generic_config }} settings.token_endpoint {{ keycloak_token_url }}"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      when: "current_generic_config.settings.token_endpoint != keycloak_token_url"
    - name: Set Keycloak UserInfo URL
      command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cset {{ drupal_generic_config }} settings.userinfo_endpoint {{ keycloak_userinfo_url }}"
      args:
        chdir: "{{ drupal_deploy_dir }}"
      when: "current_generic_config.settings.userinfo_endpoint != keycloak_userinfo_url"
