---
- name: Get Core Extensions
  command: "{{ drush_path }} --root={{ drupal_deploy_dir }} cget core.extension"
  args:
    chdir: "{{ drupal_deploy_dir }}"
  register: drupal_site_installed
  failed_when: "drupal_site_installed.stdout is undefined"
  changed_when: false
  become: "{{ drupal_core_owner_become }}"
  become_user: "{{ drupal_core_owner }}"
- name: Enable OpenID Connect (if not already)
  command: "{{ drush_path }} --root={{ drupal_deploy_dir }} pm:enable openid_connect"
  args:
    chdir: "{{ drupal_deploy_dir }}"
  when: "'openid_connect' not in (drupal_site_installed.stdout | from_yaml).module.keys()"
  become: "{{ drupal_core_owner_become }}"
  become_user: "{{ drupal_core_owner }}"
