- src: pacifica.ansible_certinfra
- src: pacifica.ansible_keycloak
- src: geerlingguy.repo-remi
- src: geerlingguy.apache
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.mysql
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: geerlingguy.git
- src: geerlingguy.composer
- src: geerlingguy.drush
- src: geerlingguy.drupal
