---
php_version: "7.4"
php_enable_webserver: false
php_enablerepo: "remi,remi-php74"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

drupal_build_composer_project: true
drupal_composer_project_package: "drupal/recommended-project:^8@dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
apache_remove_default_vhost: true
apache_vhosts_ssl:
  - servername: "localhost"
    serveralias: "localhost.localdomain"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: /etc/pki/tls/certs/localhost.localdomain.crt
    certificate_key_file: /etc/pki/tls/private/localhost.localdomain.pem
    certificate_chain_file: /etc/pki/tls/certs/pacifica_chain.io.crt
    extra_parameters: |
          <FilesMatch \.php$>
            SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
          </FilesMatch>
apache_vhosts:
  - servername: "localhost"
    serveralias: "localhost.localdomain"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
      RewriteEngine On
      RewriteCond %{HTTPS} !=on
      RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
mysql_python_package_debian: python3-mysqldb
mysql_enablerepo: "remi"
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"
drupal_composer_dependencies:
  - "drush/drush:^10.1"
  - "drupal/keycloak"
